panda/buysell/urls.py
from django.urls import path
from . import views

app_name = 'buysell'

urlpatterns = [
	path('', views.index, name='index'),
	path('signup/', views.signup, name='signup'),
	path('confirm/', views.confirm, name='confirm'),
	path('contin/<str:user_name>/', views.contin, name='contin'),
	path('login/', views.login, name='login'),
	path('postfeed/', views.postfeed, name='postfeed'),
	]

panda/panda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('home/', include('buysell.urls')),
    path('admin/', admin.site.urls),
]

panda/buysell/models.py
from django.db import models

class Account(models.Model):
	firstName = models.CharField(max_length=200)
	lastName = models.CharField(max_length=200)
	username = models.CharField(max_length=200, primary_key=True)
	email = models.CharField(max_length=200)
	password = models.CharField(max_length=200)
	datecreated = models.DateTimeField('Date Created')

	def __str__(self):
		return self.username

panda/buysell/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Account
from django.utils import timezone

def index(request):
	return render(request, 'buysell/index.html')

def signup(request):
	return render(request, 'buysell/signup.html')

def confirm(request):
	empty_field = "This field can't be empty"
	errors = dict()

	first_name = request.POST['inputFirstName']
	if not first_name:
		errors['error_first_name'] = empty_field
		
	last_name = request.POST['inputLastName']
	if not last_name:
		errors['error_last_name'] = empty_field
		
	user_name = request.POST['inputUserName']
	if not user_name:
		errors['error_user_name'] = empty_field
		
	e_mail = request.POST['inputEmail']
	if not e_mail:
		errors['error_email'] = empty_field
		
	first_password = request.POST['inputPass']
	if not first_password:
		errors['error_first_password'] = empty_field
		
	second_password = request.POST['inputPassword']
	if not second_password:
		errors['error_second_password'] = empty_field

	if (first_name and last_name and user_name and e_mail and first_password and second_password):
		if first_password == second_password:
			account = Account(firstName=first_name, lastName=last_name, username=user_name, email=e_mail, 
				password=first_password, datecreated=timezone.now())
			account.save()
			user_name = account.username
			return HttpResponseRedirect(reverse('buysell:contin', args=(user_name,)))
		else:
			error_password = "Passwords don't match"
			return render(request, 'buysell/signup.html', {'error_password': error_password})
	else:
		return render(request, 'buysell/signup.html', {'errors': errors})

def contin(request, user_name):
	account = Account.objects.get(pk=user_name)
	return render(request, 'buysell/contin.html', {'account': account})

def login(request):
	empty_field = "This field cannot be empty"
	errors = dict()

	user_name = request.POST['inputUserName']
	if not user_name:
		errors['empty_user_name'] = empty_field

	pass_word = request.POST['passWord']
	if not pass_word:
		errors['empty_password'] = empty_field

	if user_name and pass_word:
		try:
			account = Account.objects.get(pk=user_name)
		except Account.DoesNotExist:
			error_message = "Incorrect User Name"
			return render(request, 'buysell/index.html', {'error_message': error_message})
		else:
			if pass_word == account.password:
				return HttpResponseRedirect(reverse('buysell:postfeed'))
			else:
				error_password = "Incorrect Password"
				return render(request, 'buysell/index.html', {'error_password': error_password})
	else:
		return render(request, 'buysell/index.html', {'errors': errors})

def postfeed(request):
	return HttpResponse("Bro, Siraj, you are on track")

panda/buysell/templates/buysell/contin.html
<h1>{{ account.firstName }}</h1>

panda/buysell/templates/buysell/index.html
<DOCTYPE! HTML>
<html>

<head>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'buysell/index.css' %}" media="screen">
</head>

<body class="bd">

<div>
</div>

<div id="title">
	<h1>PANDA</h1>
	<br/>
	<p>World's best site for selling and buying used and unused products</p>
</div>

<div id="footer"></div>


<div id="wrapper">
	<h2><a href="{% url 'buysell:signup' %}">SIGN UP</a></h2>
	<form action="{% url 'buysell:login' %}" method="post" class="formclass">
		{% csrf_token %}
		<p>User Name</p>
		<input type="text" name="inputUserName" size="30" />
		<label for="inputUserName" id="error_label"><br/>{{ error_message }}</label>
		<label for="inputUserName" id="error_label"><br/>{{ errors.empty_user_name }}</label>
		<br/><br/><br/><br/>
		<p>Password</p>
		<input type="password" name="passWord" size="30" />
		<label for="passWord" id="error_label"><br/>{{ error_password }}</label>
		<label for="passWord" id="error_label"><br/>{{ errors.empty_password }}</label>
		<br/><br/><br/>
		<input type="submit" value="Log In" id="sub">
	</form>
	<h2><a href="">FORGOT PASSWORD?</a></h2>
</div>

<div id="footer"></div>


</body>

</html>

panda/buysell/templates/buysell/signup.html
<DOCTYPE! HTML>
<html>

<head>
	{% load static %}
	<link rel="stylesheet" id="fixed-width-wrapper" type="text/css" href="{% static 'buysell/signup.css' %}" media="screen">
	<link rel="stylesheet" id="fixed-width-wrapper" type="text/css" href="{% static 'buysell/index.css' %}" media="screen">
</head>

<body class="bd">
	<div ></div>

	<div id="title" class="header">
	<h1>PANDA</h1>
	<br/>
	<p>World's best site for selling and buying used and unused products</p>
	</div>

	<div id="myfooter"></div>

	<div id="wrapper">
		<form action="{% url 'buysell:confirm' %}" method="post" class="formclass">
			{% csrf_token %}
			<h2>Fill the form below to create an account</h2>
			<p>Enter First Name</p>
			<input type="text" id="input" name="inputFirstName" size="30" />
			<label for="inputPassword" id="error_label"><br/>
				{{ errors.error_first_name }}
			</label>
			<p>Enter Last Name</p>
			<input type="text" id="input" name="inputLastName" size="30"/>
			<label for="inputPassword" id="error_label"><br/>
				{{ errors.error_last_name }}
			</label>
			<p>Enter User Name</p>
			<input type="text" id="input" name="inputUserName" size="30"/>
			<label for="inputPassword" id="error_label"><br/>
				{{ errors.error_user_name }}
			</label>
			<p>Enter E-mail</p>
			<input type="text" id="input" name="inputEmail" size="30"/>
			<label for="inputPassword" id="error_label"><br/>
				{{ errors.error_email }}
			</label>
			<p>Enter Password</p>
			<input type="password" id="input" name="inputPass" size="30"/>
			<label for="inputPassword" id="error_label"><br/>
				{{ errors.error_first_password }}
			</label>
			<p>Enter Password Again</p>
			<input type="password" name="inputPassword" size="30"/>		
			<label for="inputPassword" id="error_label"><br/>
				{{ error_password }}
				{{ errors.error_second_password}}
			</label>
			<br/><br/>
			<input type="submit" value="Submit" id="sub">
		</form>
	</div>

	<div id="myfooter"></div>
</body>

</html>